In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
import numpy as np

In [2]:
df=pd.read_csv('amazon_laptop_Data_2025-07-27.csv')
df2=pd.read_csv('amazon_laptop_Data2025-08-01.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319 entries, 0 to 318
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            319 non-null    int64
 1   rating                319 non-null    float64
 2   reviews               319 non-null    float64
 3   extracted_price       319 non-null    float64
 4   asin                  319 non-null    object
 5   title                 319 non-null    object
 6   link_clean            319 non-null    object
 7   thumbnail             319 non-null    object
 8   delivery              319 non-null    object
 9   display_size          319 non-null    object
 10  ram                   319 non-null    object
 11  disk_size             319 non-null    object
 12  operating_system      319 non-null    object
 13  Price(indian_rupees)  319 non-null    int64
 14  scrape_date           319 non-null    object
dtypes: float64(3), int64(2), object(10)
memory usage: 37.5+ KB

In [5]:
df.columns

Index(['Unnamed: 0', 'rating', 'reviews', 'extracted_price', 'asin', 'title',
       'link_clean', 'thumbnail', 'delivery', 'display_size', 'ram',
       'disk_size', 'operating_system', 'Price(indian_rupees)', 'scrape_date'],
      dtype='object')

In [4]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                432 non-null    int64
 1   position                  432 non-null    int64
 2   asin                      432 non-null    object
 3   sponsored                 126 non-null    object
 4   options                   216 non-null    object
 5   options_link              216 non-null    object
 6   title                     432 non-null    object
 7   link                      432 non-null    object
 8   link_clean                432 non-null    object
 9   thumbnail                 432 non-null    object
 10  rating                    421 non-null    float64
 11  reviews                   421 non-null    float64
 12  bought_last_month         290 non-null    object
 13  price                     428 non-null    object
 14  extracted_price           428 non-null    float64
 15  old_price                 193 non-null    object
 16  extracted_old_price       193 non-null    float64
 17  specs                     423 non-null    object
 18  delivery                  424 non-null    object
 19  variants                  69 non-null     object
 20  badges                    68 non-null     object
 21  more_buying_choices       143 non-null    object
 22  more_buying_choices_link  143 non-null    object
 23  climate_pledge_friendly   12 non-null     object
 24  sustainability_features   12 non-null     object
 25  stock                     99 non-null     object
 26  offers                    27 non-null     object
 27  save_with_coupon          19 non-null     object
 28  small_business            19 non-null     object
 29  price_unit                1 non-null      object
 30  extracted_price_unit      1 non-null      float64
 31  works_with_alexa          2 non-null      object
 32  scrape_date               432 non-null    object
dtypes: float64(5), int64(2), object(26)
memory usage: 111.5+ KB

In [5]:
df.isnull().sum()

Unnamed: 0              0
rating                  0
reviews                 0
extracted_price         0
asin                    0
title                   0
link_clean              0
thumbnail               0
delivery                0
display_size            0
ram                     0
disk_size               0
operating_system        0
Price(indian_rupees)    0
scrape_date             0
dtype: int64

In [6]:
df2=df2[['asin','title','link_clean','thumbnail','rating','reviews','extracted_price','specs','delivery','scrape_date']]
df=df[['asin','title','link_clean','thumbnail','rating','reviews','extracted_price','display_size','ram','disk_size','operating_system','delivery','scrape_date']]

In [7]:
df.duplicated().sum()

np.int64(28)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 291 entries, 0 to 318
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   asin              291 non-null    object
 1   title             291 non-null    object
 2   link_clean        291 non-null    object
 3   thumbnail         291 non-null    object
 4   rating            291 non-null    float64
 5   reviews           291 non-null    float64
 6   extracted_price   291 non-null    float64
 7   display_size      291 non-null    object
 8   ram               291 non-null    object
 9   disk_size         291 non-null    object
 10  operating_system  291 non-null    object
 11  delivery          291 non-null    object
 12  scrape_date       291 non-null    object
dtypes: float64(3), object(10)
memory usage: 31.8+ KB

In [11]:
def datatype_conversion(df,col):
    return df[col].astype(float)

In [12]:
def dollar_to_ruppe(col):
    return int(col*86.46)

In [15]:
def handle_specs(df):
    return df.fillna('Info Not Available !')

In [16]:
# specs_df = df['specs'].apply(parse_specs)
# df = pd.concat([df, specs_df], axis=1)
# df.drop(columns=['specs'], inplace=True)

specs_df2 = df2['specs'].apply(parse_specs)
df2 = pd.concat([df2, specs_df2], axis=1)
df2.drop(columns=['specs'], inplace=True)

In [17]:
df=handle_missing_values(df)
df2=handle_missing_values(df2)

In [18]:
df[['reviews','rating','extracted_price']]=datatype_conversion(df,['reviews','rating','extracted_price'])
df2[['reviews','rating','extracted_price']]=datatype_conversion(df2,['reviews','rating','extracted_price'])

In [19]:
df['Price(indian_rupees)']=df['extracted_price'].apply(dollar_to_ruppe)
df2['Price(indian_rupees)']=df2['extracted_price'].apply(dollar_to_ruppe)

In [20]:
df[['ram','display_size','operating_system','disk_size']]=df[['ram','display_size','operating_system','disk_size']].apply(handle_specs)
df2[['ram','display_size','operating_system','disk_size']]=df2[['ram','display_size','operating_system','disk_size']].apply(handle_specs)

In [21]:
df['scrape_date'] = pd.to_datetime(df['scrape_date']) 
df2['scrape_date'] = pd.to_datetime(df2['scrape_date'])

In [22]:
# df['delivery']=df['delivery'].apply(clean_delivery)
df2['delivery']=df2['delivery'].apply(clean_delivery)

FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
Available now
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery
FREE delivery

In [23]:
df2.head()

,rating,reviews,extracted_price,asin,title,link_clean,thumbnail,delivery,scrape_date,display_size,ram,disk_size,operating_system,Price(indian_rupees)
0,4.2,127.0,589.99,B0DW5Z3S2R,"Lenovo IdeaPad 15.6” FHD Touchscreen Laptop, 4...",https://www.amazon.com/dp/B0DW5Z3S2R/,https://m.media-amazon.com/images/I/71S+P-5tdp...,FREE delivery,2025-08-01,15.6 inches,40 GB,2.5 TB,Windows 11 Pro,51010
1,3.6,24.0,489.99,B0F8PB2HNL,"Lenovo IdeaPad 15.6"" Laptop, 36GB RAM 2.6TB St...",https://www.amazon.com/dp/B0F8PB2HNL/,https://m.media-amazon.com/images/I/61+HL6QmgL...,FREE delivery,2025-08-01,15.6 inches,36 GB,2.6 TB,Windows 11 Pro,42364
2,5.0,33.0,209.99,B0FFSPXRGN,"15.6 Inch Laptop with Office 365, 4GB RAM, 128...",https://www.amazon.com/Expandable-Processor-Co...,https://m.media-amazon.com/images/I/71vwx59yoV...,FREE delivery,2025-08-01,15.6 inches,-,128 GB,Windows 11,18155
3,4.8,1474.0,799.00,B0DZDC3WW5,Apple 2025 MacBook Air 13-inch Laptop with M4 ...,https://www.amazon.com/Apple-2025-MacBook-13-i...,https://m.media-amazon.com/images/I/712dp0yAyd...,FREE delivery,2025-08-01,13.6 inches,16.00 GB,256 GB,Mac OS,69081
4,4.1,3617.0,173.50,B0947BJ67M,"HP 14 Laptop, Intel Celeron N4020, 4 GB RAM, 6...",https://www.amazon.com/HP-Micro-edge-Microsoft...,https://m.media-amazon.com/images/I/815uX7wkOZ...,FREE delivery,2025-08-01,14 inches,4 GB,64 GB,Windows 11 S,15000

In [24]:
df_merged = pd.merge(df, df2, on='asin', how='inner', suffixes=('_old', '_new'))

In [26]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   rating_old                194 non-null    float64
 1   reviews_old               194 non-null    float64
 2   extracted_price_old       194 non-null    float64
 3   asin                      194 non-null    object
 4   title_old                 194 non-null    object
 5   link_clean_old            194 non-null    object
 6   thumbnail_old             194 non-null    object
 7   display_size_old          194 non-null    object
 8   ram_old                   194 non-null    object
 9   disk_size_old             194 non-null    object
 10  operating_system_old      194 non-null    object
 11  delivery_old              194 non-null    object
 12  scrape_date_old           194 non-null    datetime64[ns]
 13  Price(indian_rupees)_old  194 non-null    int64
 14  rating_new                194 non-null    float64
 15  reviews_new               194 non-null    float64
 16  extracted_price_new       194 non-null    float64
 17  title_new                 194 non-null    object
 18  link_clean_new            194 non-null    object
 19  thumbnail_new             194 non-null    object
 20  delivery_new              194 non-null    object
 21  scrape_date_new           194 non-null    datetime64[ns]
 22  display_size_new          194 non-null    object
 23  ram_new                   194 non-null    object
 24  disk_size_new             194 non-null    object
 25  operating_system_new      194 non-null    object
 26  Price(indian_rupees)_new  194 non-null    int64
dtypes: datetime64[ns](2), float64(6), int64(2), object(17)
memory usage: 41.1+ KB

In [38]:
df_merged['price_diff']=df_merged['extracted_price_new']-df_merged['extracted_price_old']
df_merged['price_diff_percentage']=(df_merged['price_diff']/df_merged['extracted_price_old'])*100

df_merged['price_drop_flag'] = df_merged['price_diff_percentage'] <= -5  
df_merged['price_rise_flag'] = df_merged['price_diff_percentage'] >= 5   

df_merged['rating_diff'] = df_merged['rating_new'] - df_merged['rating_old']
df_merged['buy_now'] = (df_merged['price_drop_flag']) & (df_merged['rating_new'] >= 3.5)

In [44]:
df_merged.head(3)['link_clean_new'][1]

'https://www.amazon.com/15-6-FHD-IPS-Student-Laptop-Computer-Fingerprint/dp/B0FDQ775FY/'

In [47]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   rating_old                194 non-null    float64
 1   reviews_old               194 non-null    float64
 2   extracted_price_old       194 non-null    float64
 3   asin                      194 non-null    object
 4   title_old                 194 non-null    object
 5   link_clean_old            194 non-null    object
 6   thumbnail_old             194 non-null    object
 7   display_size_old          194 non-null    object
 8   ram_old                   194 non-null    object
 9   disk_size_old             194 non-null    object
 10  operating_system_old      194 non-null    object
 11  delivery_old              194 non-null    object
 12  scrape_date_old           194 non-null    datetime64[ns]
 13  Price(indian_rupees)_old  194 non-null    int64
 14  rating_new                194 non-null    float64
 15  reviews_new               194 non-null    float64
 16  extracted_price_new       194 non-null    float64
 17  title_new                 194 non-null    object
 18  link_clean_new            194 non-null    object
 19  thumbnail_new             194 non-null    object
 20  delivery_new              194 non-null    object
 21  scrape_date_new           194 non-null    datetime64[ns]
 22  display_size_new          194 non-null    object
 23  ram_new                   194 non-null    object
 24  disk_size_new             194 non-null    object
 25  operating_system_new      194 non-null    object
 26  Price(indian_rupees)_new  194 non-null    int64
 27  price_diff                194 non-null    float64
 28  price_diff_percentage     194 non-null    float64
 29  price_drop_flag           194 non-null    bool
 30  price_rise_flag           194 non-null    bool
 31  rating_diff               194 non-null    float64
 32  buy_now                   194 non-null    bool
dtypes: bool(3), datetime64[ns](2), float64(9), int64(2), object(17)
memory usage: 46.2+ KB

In [45]:
df_merged.to_csv('Amazon_laptop_data.csv')